Handle pending transaction replace
reef-defi/reef-client pull request #312
Opened 2021-04-01 21:20 UTC by matjazonline

2021-04-02 08:55 UTC, obenyahya requested changes

2021-04-02 08:55 UTC, obenyahya commented on src/app/core/services/transactions.service.ts
> +              : info.chainInfo.name,
can you please move this bellow txUrl and create a const called for exemple scannerName ?

2021-04-02 08:55 UTC, obenyahya commented on src/app/core/services/transactions.service.ts
> +        const { blockHash, blockNumber } = trx;
can you please add the unit tests

2021-04-02 08:57 UTC, obenyahya requested changes

2021-04-02 08:57 UTC, obenyahya commented on src/app/core/services/transactions.service.ts
> +    if (!hash || transactions.find((tx) => tx.hash === hash)) {
can you please create a const for transactions.find((tx) => tx.hash === hash) above ot th if condition ?

2021-04-16 10:21 UTC, filipbarak approved these changes

2021-04-16 10:21 UTC, merged